export interface CareerContent {
  title: string;
  tagline: string;
  badge: string;
  aboutTitle: string;
  aboutParagraphs: string[];
  rolesTitle: string;
  rolesDescription: string;
  roles: {
    title: string;
    description: string;
  }[];
  ladderTitle: string;
  ladderSteps: {
    step: string;
    role: string;
    experience: string;
    description: string;
  }[];
  skillsTitle: string;
  skills: string[];
  sectorsTitle: string;
  sectors: {
    name: string;
    description: string;
  }[];
  relatedCoursesTitle: string;
  relatedCourses: {
    code: string;
    title: string;
    duration: string;
    eligibility: string;
    href: string;
  }[];
  ctaTitle: string;
  ctaDescription: string;
  ctaButtonText: string;
}

export interface CareerItem {
  id: number;
  slug: string;
  image: string;
  stats: {
    durationEn: string;
    durationHi: string;
    eligibilityEn: string;
    eligibilityHi: string;
    salaryEn: string;
    salaryHi: string;
    demandEn: string;
    demandSubEn?: string;
    demandHi: string;
    demandSubHi?: string;
  };
  en: CareerContent;
  hi: CareerContent;
}

export const CAREERS_DATA: CareerItem[] = [
  {
    id: 1,
    slug: "medical-lab-tech",
    image: "/Meditech1.jpeg",
    stats: {
      durationEn: "1 - 2 Years",
      durationHi: "1 से 2 वर्ष",
      eligibilityEn: "10th / 12th (Science/PCB)",
      eligibilityHi: "10वीं / 12वीं (साइंस/PCB)",
      salaryEn: "₹20,000 - ₹50,000 / mo",
      salaryHi: "₹20,000 - ₹50,000 प्रति माह",
      demandEn: "Very High",
      demandSubEn: "Hospitals & Diagnostics",
      demandHi: "अत्यधिक मांग",
      demandSubHi: "अस्पताल व पैथोलॉजी लैब्स",
    },
    en: {
      title: "Medical Laboratory Technician (MLT)",
      tagline: "The Diagnostic Backbone of Modern Healthcare & Pathology Science",
      badge: "National Board Certified Specialization",
      aboutTitle: "About the Medical Lab Technology Profession",
      aboutParagraphs: [
        "Medical Laboratory Technicians (MLT) play a crucial diagnostic role in modern medicine. Over 70% of medical decisions taken by physicians and surgeons depend directly on pathological, biochemical, and hematological test results generated by clinical laboratory specialists.",
        "As a certified Medical Lab Technician, you operate advanced automated analysers, prepare blood and tissue specimens, analyze microscopic cultures, detect infectious organisms, and maintain stringent biosafety standards in diagnostic laboratories and hospitals."
      ],
      rolesTitle: "Key Roles & Responsibilities",
      rolesDescription: "Essential technical duties carried out daily in diagnostic and pathology laboratories:",
      roles: [
        {
          title: "Specimen Collection & Handling",
          description: "Safely collect, preserve, and label blood samples, fluids, and tissue specimens adhering to phlebotomy protocols."
        },
        {
          title: "Clinical Testing & Analysis",
          description: "Perform hematology, clinical biochemistry, serology, microbiology, and urinalysis tests with high precision."
        },
        {
          title: "Operating Automated Analysers",
          description: "Calibrate and operate computerized laboratory instruments like automated hematology counters and spectrophotometers."
        },
        {
          title: "Quality Assurance & Calibration",
          description: "Run standard control samples daily, recognize discrepancies, and ensure diagnostic accuracy according to NABL standards."
        },
        {
          title: "Documentation & Reporting",
          description: "Accurately record quantitative test metrics into Laboratory Information Management Systems (LIMS) for pathologist validation."
        },
        {
          title: "Biohazard Safety & Disinfection",
          description: "Strictly implement biomedical waste management, autoclave sterilization, and infectious disease safety protocols."
        }
      ],
      ladderTitle: "Career Progression Pathway",
      ladderSteps: [
        {
          step: "01",
          role: "Trainee / Junior Lab Tech",
          experience: "0 - 1 Year",
          description: "Assisting senior technicians in sample sorting, routine testing, and basic equipment upkeep."
        },
        {
          step: "02",
          role: "Medical Lab Technician (MLT)",
          experience: "1 - 3 Years",
          description: "Independent execution of specialized biochemical, immunological, and microbial investigations."
        },
        {
          step: "03",
          role: "Senior Lab Technologist",
          experience: "3 - 6 Years",
          description: "Overseeing test validation, automated instrument calibration, and quality control auditing."
        },
        {
          step: "04",
          role: "Laboratory In-Charge / Supervisor",
          experience: "6+ Years",
          description: "Managing entire diagnostic lab operations, compliance, staff supervision, and doctor liaisons."
        }
      ],
      skillsTitle: "Key Technical & Clinical Skills Acquired",
      skills: [
        "Clinical Pathology & Hematology",
        "Biochemistry & Immunoassays",
        "Microbiology & Culture Staining",
        "Automated Cell Counters Operation",
        "Phlebotomy & Sample Preservation",
        "LIMS & Digital Health Records",
        "Biomedical Waste Disposal",
        "Laboratory Quality Control"
      ],
      sectorsTitle: "Top Employment Sectors",
      sectors: [
        {
          name: "Government & Private Hospitals",
          description: "Central emergency and indoor pathology testing departments."
        },
        {
          name: "Diagnostic Chains & Pathology Labs",
          description: "High-volume testing centers (e.g., Dr. Lal PathLabs, Thyrocare, SRL)."
        },
        {
          name: "Blood Banks & Transfusion Units",
          description: "Donor screening, cross-matching, and blood component separation."
        },
        {
          name: "Pharmaceutical & Clinical Research Labs",
          description: "Drug trial monitoring, toxicology tests, and biological assays."
        }
      ],
      relatedCoursesTitle: "Board Certified Courses for this Career",
      relatedCourses: [
        {
          code: "DMLT",
          title: "Diploma in Medical Laboratory Technology",
          duration: "2 Years",
          eligibility: "10+2 with Science (PCB)",
          href: "/courses"
        },
        {
          code: "CMLT",
          title: "Certificate in Medical Laboratory Technology",
          duration: "1 Year",
          eligibility: "10th / 10+2 Pass",
          href: "/courses"
        }
      ],
      ctaTitle: "Ready to Build Your Career in Medical Laboratory Science?",
      ctaDescription: "Enrol in a recognized paramedical diploma or certificate program through affiliated institutions of the Indian Paramedical Board of India.",
      ctaButtonText: "Explore Courses & Apply"
    },
    hi: {
      title: "मेडिकल लैबोरेट्री तकनीशियन (MLT)",
      tagline: "आधुनिक चिकित्सा एवं पैथोलॉजी विज्ञान की सबसे महत्वपूर्ण रीढ़",
      badge: "राष्ट्रीय बोर्ड द्वारा मान्यता प्राप्त विशेषज्ञता",
      aboutTitle: "मेडिकल लैब टेक्नोलॉजी करियर का परिचय",
      aboutParagraphs: [
        "मेडिकल लैबोरेट्री तकनीशियन (MLT) आधुनिक स्वास्थ्य सेवा में अत्यंत महत्वपूर्ण भूमिका निभाते हैं। डॉक्टरों और सर्जनों द्वारा लिए जाने वाले 70% से अधिक चिकित्सीय निर्णय पैथोलॉजिकल, बायोकेमिकल और ब्लड टेस्ट रिपोर्ट पर निर्भर करते हैं।",
        "एक प्रमाणित मेडिकल लैब तकनीशियन के रूप में आप आधुनिक ऑटोमेटेड एनालाइजर संचालित करते हैं, रक्त एवं ऊतकों (टिश्यू) के नमूनों की जांच करते हैं, संक्रामक रोगों के कीटाणुओं की पहचान करते हैं और डायग्नोस्टिक लैब में उच्च सुरक्षा मानकों का पालन करते हैं।"
      ],
      rolesTitle: "मुख्य कार्य एवं जिम्मेदारियाँ",
      rolesDescription: "डायग्नोस्टिक और पैथोलॉजी लैब में रोजाना किए जाने वाले प्रमुख तकनीकी कर्तव्य:",
      roles: [
        {
          title: "नमूना संग्रह एवं प्रबंधन (Sample Collection)",
          description: "मरीजों से सुरक्षित तरीके से खून व अन्य शारीरिक नमूनों को एकत्रित करना और उनका सही लेबलिंग करना।"
        },
        {
          title: "क्लिनिकल परीक्षण एवं जांच (Clinical Testing)",
          description: "रक्त की जांच (Hematology), बायोकेमिस्ट्री, सीरोलॉजी, और यूरिन टेस्ट सटीक तरीके से संपन्न करना।"
        },
        {
          title: "ऑटोमेटेड मशीनों का संचालन",
          description: "कंप्यूटराइज्ड लैब उपकरणों जैसे ऑटोमेटेड सेल काउंटर और स्पेक्ट्रोफोटोमीटर को सही तरीके से चलाना।"
        },
        {
          title: "गुणवत्ता नियंत्रण (Quality Control)",
          description: "प्रतिदिन कंट्रोल सैंपल टेस्ट करना, रीडिंग में किसी भी त्रुटि की पहचान करना और NABL मानकों का पालन करना।"
        },
        {
          title: "जांच रिपोर्ट तैयार करना",
          description: "परीक्षण के सटीक आंकड़ों को डिजिटल लैब सॉफ्टवेयर में दर्ज करना ताकि पैथोलॉजिस्ट डॉक्टर उसे प्रमाणित कर सकें।"
        },
        {
          title: "बायोहैजर्ड सुरक्षा व स्टेरलाइजेशन",
          description: "अस्पताल में बायोमेडिकल वेस्ट का सुरक्षित निपटान और लैब उपकरणों की निरंतर सफाई व रोगाणुनाशन सुनिश्चित करना।"
        }
      ],
      ladderTitle: "करियर में पदोन्नति एवं विकास क्रम",
      ladderSteps: [
        {
          step: "01",
          role: "ट्रेनी / जूनियर लैब तकनीशियन",
          experience: "0 - 1 वर्ष",
          description: "वरिष्ठ तकनीशियनों की देखरेख में सैंपल प्रोसेसिंग, बेसिक टेस्ट और मशीनों की सफाई का कार्य।"
        },
        {
          step: "02",
          role: "मेडिकल लैब तकनीशियन (MLT)",
          experience: "1 - 3 वर्ष",
          description: "स्वतंत्र रूप से जटिल बायोकेमिकल, माइक्रोबायोलॉजी और सीरोलॉजिकल टेस्ट्स का संचालन।"
        },
        {
          step: "03",
          role: "सीनियर लैब टेक्नोलॉजिस्ट",
          experience: "3 - 6 वर्ष",
          description: "रिपोर्ट्स का सत्यापन, ऑटोमेटेड एनालाइजर कैलिब्रेशन और लैब क्वालिटी कंट्रोल की जिम्मेदारी।"
        },
        {
          step: "04",
          role: "लैब सुपरवाइजर / इंचार्ज",
          experience: "6+ वर्ष",
          description: "संपूर्ण डायग्नोस्टिक लैब का संचालन, कर्मचारियों का प्रबंधन और डॉक्टरों के साथ समन्वय।"
        }
      ],
      skillsTitle: "प्रशिक्षण के दौरान अर्जित मुख्य कौशल",
      skills: [
        "क्लिनिकल पैथोलॉजी एवं हेमेटोलॉजी",
        "बायोकेमिस्ट्री एवं इम्यूनोएस्से",
        "माइक्रोबायोलॉजी एवं कल्चर स्टेनिंग",
        "ऑटोमेटेड लैब एनालाइजर संचालन",
        "फ्लेबोटोमी एवं सैंपल प्रिजर्वेशन",
        "डिजिटल लैब सॉफ्टवेयर (LIMS)",
        "बायोमेडिकल वेस्ट मैनेजमेंट",
        "लैबोरेट्री गुणवत्ता आश्वासन (QA)"
      ],
      sectorsTitle: "प्रमुख रोजगार क्षेत्र",
      sectors: [
        {
          name: "सरकारी एवं निजी अस्पताल",
          description: "सेंट्रल इमरजेंसी पैथोलॉजी और इनडोर टेस्टिंग डिपार्टमेंट्स।"
        },
        {
          name: "डायग्नोस्टिक चेन्स एवं पैथोलॉजी सेंटर्स",
          description: "प्रमुख डायग्नोस्टिक लैब्स (जैसे डॉ. लाल पैथलैब्स, थायरोकेयर, एसआरएल आदि)।"
        },
        {
          name: "ब्लड बैंक्स एवं ट्रांसफ्यूजन यूनिट्स",
          description: "रक्तदाताओं की जांच, ब्लड ग्रुप मैचिंग और कंपोनेंट सेपरेशन का कार्य।"
        },
        {
          name: "फार्मास्युटिकल एवं क्लिनिकल रिसर्च",
          description: "दवा परीक्षण, टॉक्सिकोलॉजी टेस्ट्स और मेडिकल रिसर्च प्रोजेक्ट्स।"
        }
      ],
      relatedCoursesTitle: "इस करियर के लिए बोर्ड से जुड़े कोर्सेज",
      relatedCourses: [
        {
          code: "DMLT",
          title: "डिप्लोमा इन मेडिकल लैबोरेट्री टेक्नोलॉजी",
          duration: "2 वर्ष",
          eligibility: "10+2 (साइंस / PCB)",
          href: "/courses"
        },
        {
          code: "CMLT",
          title: "सर्टिफिकेट इन मेडिकल लैबोरेट्री टेक्नोलॉजी",
          duration: "1 वर्ष",
          eligibility: "10वीं / 10+2 उत्तीर्ण",
          href: "/courses"
        }
      ],
      ctaTitle: "क्या आप मेडिकल लैब टेक्नोलॉजी में करियर शुरू करने के लिए तैयार हैं?",
      ctaDescription: "इंडियन पैरामेडिकल बोर्ड ऑफ इंडिया के संबद्ध संस्थानों से मान्यता प्राप्त डिप्लोमा या सर्टिफिकेट कोर्स में प्रवेश लें।",
      ctaButtonText: "कोर्सेज देखें एवं आवेदन करें"
    }
  },
  {
    id: 2,
    slug: "radiographer",
    image: "/Meditech2.jpeg",
    stats: {
      durationEn: "1 - 2 Years",
      durationHi: "1 से 2 वर्ष",
      eligibilityEn: "10+2 with Physics & Chemistry",
      eligibilityHi: "10+2 (फिजिक्स एवं केमिस्ट्री)",
      salaryEn: "₹22,000 - ₹55,000 / mo",
      salaryHi: "₹22,000 - ₹55,000 प्रति माह",
      demandEn: "High Demand",
      demandSubEn: "Trauma & Imaging Centers",
      demandHi: "उच्च मांग",
      demandSubHi: "ट्रॉमा व सीटी/एमआरआई सेंटर्स",
    },
    en: {
      title: "Radiographer & Medical Imaging Specialist",
      tagline: "Pioneering Internal Diagnostics through X-Ray, CT Scan, and MRI Imaging",
      badge: "High Precision Imaging Specialization",
      aboutTitle: "About the Radiography & Imaging Career",
      aboutParagraphs: [
        "Radiographers and Medical Imaging Technologists are allied health professionals trained to capture high-clarity images of bones, tissues, and internal organs. They assist radiologists in detecting fractures, tumors, internal hemorrhages, and cardiac abnormalities.",
        "With rapid advancements in digital radiography, multi-slice computed tomography (CT), magnetic resonance imaging (MRI), and fluoroscopy, certified radiographers are among the highest-sought specialists in emergency medicine and surgical trauma centers."
      ],
      rolesTitle: "Key Roles & Responsibilities",
      rolesDescription: "Essential technical duties carried out daily in radiology and imaging suites:",
      roles: [
        {
          title: "Patient Positioning & Preparation",
          description: "Comfortably and precisely position patients on imaging tables to obtain accurate diagnostic projections."
        },
        {
          title: "Operating High-End Imaging Systems",
          description: "Configure exposure parameters (kVp, mAs) and capture radiographs using digital X-ray, CT scan, or MRI units."
        },
        {
          title: "Radiation Safety & Lead Shielding",
          description: "Implement ALARA (As Low As Reasonably Achievable) principles and place lead aprons to shield vital patient organs."
        },
        {
          title: "Image Processing & PACS Archival",
          description: "Enhance digital radiograph contrast and securely transmit images to the hospital PACS system for radiologist review."
        },
        {
          title: "Assisting in Contrast Procedures",
          description: "Prepare and monitor non-ionic iodinated contrast media under radiologist guidance for fluoroscopic studies."
        },
        {
          title: "Equipment Calibration & QA",
          description: "Perform routine calibration of X-ray tubes, sensors, and safety monitors in line with AERB compliance."
        }
      ],
      ladderTitle: "Career Progression Pathway",
      ladderSteps: [
        {
          step: "01",
          role: "Junior X-Ray Technician",
          experience: "0 - 1 Year",
          description: "Handling conventional digital radiographs, patient immobilization, and dark room / PACS processing."
        },
        {
          step: "02",
          role: "Clinical Radiographer",
          experience: "1 - 3 Years",
          description: "Performing specialized musculoskeletal, chest, and emergency trauma X-rays independently."
        },
        {
          step: "03",
          role: "CT / MRI Imaging Specialist",
          experience: "3 - 6 Years",
          description: "Handling complex cross-sectional multi-slice CT scans, cardiac MRI, and angio-interventional procedures."
        },
        {
          step: "04",
          role: "Chief Radiologic Technologist",
          experience: "6+ Years",
          description: "Managing radiology suite workflow, radiation protection compliance, and equipment procurement."
        }
      ],
      skillsTitle: "Key Technical & Clinical Skills Acquired",
      skills: [
        "Digital Radiography (DR/CR Systems)",
        "CT Scan Protocol Configuration",
        "MRI Safety & Magnet Protocol",
        "Radiation Shielding & AERB Guidelines",
        "Patient Anatomical Positioning",
        "PACS & Digital Imaging Software",
        "Contrast Media Management",
        "Emergency Trauma Imaging"
      ],
      sectorsTitle: "Top Employment Sectors",
      sectors: [
        {
          name: "Multi-Specialty Hospitals & Trauma Centers",
          description: "24/7 acute trauma X-ray, ICU bedside mobile X-ray, and surgical C-Arm support."
        },
        {
          name: "Advanced Imaging & Diagnostic Centers",
          description: "Dedicated MRI, spiral CT scan, and bone densitometry centers."
        },
        {
          name: "Cancer & Oncology Institutes",
          description: "Positron emission tomography (PET-CT) and radiation oncology support."
        },
        {
          name: "Orthopedic & Sports Injury Clinics",
          description: "Bone joint alignment, spine imaging, and post-operative scans."
        }
      ],
      relatedCoursesTitle: "Board Certified Courses for this Career",
      relatedCourses: [
        {
          code: "DRT",
          title: "Diploma in Radiography Technology (X-Ray/CT)",
          duration: "2 Years",
          eligibility: "10+2 with Science (PCB/PCM)",
          href: "/courses"
        },
        {
          code: "CXRT",
          title: "Certificate in X-Ray Technician",
          duration: "1 Year",
          eligibility: "10th / 10+2 Pass",
          href: "/courses"
        }
      ],
      ctaTitle: "Advance Your Future in Medical Imaging & Radiology",
      ctaDescription: "Join recognized radiography and medical imaging programs with comprehensive hospital-based practical training.",
      ctaButtonText: "Explore Courses & Apply"
    },
    hi: {
      title: "रेडियोग्राफर एवं मेडिकल इमेजिंग तकनीशियन",
      tagline: "एक्स-रे, सीटी स्कैन और एमआरआई से शरीर के आंतरिक रोगों की सटीक पहचान",
      badge: "उच्च तकनीक आधारित मेडिकल इमेजिंग",
      aboutTitle: "रेडियोलॉजी एवं इमेजिंग करियर का परिचय",
      aboutParagraphs: [
        "रेडियोग्राफर और मेडिकल इमेजिंग टेक्नोलॉजिस्ट वे स्वास्थ्य पेशेवर होते हैं जो हड्डियों, आंतरिक अंगों और नसों के उच्च गुणवत्ता वाले चित्र (स्कैन) लेते हैं। वे रेडियोलॉजिस्ट डॉक्टरों को हड्डियों के फ्रैक्चर, ट्यूमर, आंतरिक रक्तस्राव और संक्रमण की सटीक पहचान में सहायता करते हैं।",
        "डिजिटल एक्स-रे, मल्टी-स्लाइस सीटी स्कैन और एमआरआई जैसी आधुनिक तकनीकों के आने से आज हर बड़े अस्पताल, ट्रॉमा सेंटर और डायग्नोस्टिक सेंटर में प्रमाणित रेडियोग्राफर्स की भारी मांग है।"
      ],
      rolesTitle: "मुख्य कार्य एवं जिम्मेदारियाँ",
      rolesDescription: "रेडियोलॉजी विभाग में प्रतिदिन निभाए जाने वाले प्रमुख कर्तव्य:",
      roles: [
        {
          title: "मरीज की सही स्थिति (Patient Positioning)",
          description: "मरीज को एक्स-रे या सीटी स्कैन टेबल पर सही कोण (Angle) में लेटाना या खड़ा करना ताकि सबसे स्पष्ट तस्वीर मिल सके।"
        },
        {
          title: "आधुनिक इमेजिंग मशीनों का संचालन",
          description: "एक्स-रे ट्यूब, डिजिटल सेंसर्स और सीटी स्कैनर्स के तकनीकी पैरामीटर्स सेट करके स्कैनिंग प्रक्रिया पूरी करना।"
        },
        {
          title: "रेडिएशन सुरक्षा (Radiation Safety)",
          description: "ALARA नियमों का पालन करना और मरीज के संवेदनशील अंगों को लेड एप्रन (Lead Apron) से सुरक्षित रखना।"
        },
        {
          title: "डिजिटल इमेज प्रोसेसिंग व PACS",
          description: "डिजिटल तस्वीरों की ब्राइटनेस/कंट्रास्ट को ठीक करना और कंप्यूटर नेटवर्क (PACS) पर रेडियोलॉजिस्ट को भेजना।"
        },
        {
          title: "कंट्रास्ट मीडिया का उपयोग",
          description: "विशेष स्कैन के लिए डॉक्टर के निर्देशानुसार कंट्रास्ट डाई तैयार करना और प्रक्रिया के दौरान मरीज की निगरानी करना।"
        },
        {
          title: "उपकरणों की जांच एवं रखरखाव",
          description: "एक्स-रे मशीनों का नियमित कैलिब्रेशन करना और परमाणु ऊर्जा नियामक बोर्ड (AERB) के सुरक्षा मानकों को पूरा करना।"
        }
      ],
      ladderTitle: "करियर में पदोन्नति एवं विकास क्रम",
      ladderSteps: [
        {
          step: "01",
          role: "जूनियर एक्स-रे तकनीशियन",
          experience: "0 - 1 वर्ष",
          description: "सामान्य एक्स-रे, बेडसाइड मोबाइल एक्स-रे और मरीजों की पोजिशनिंग का कार्य।"
        },
        {
          step: "02",
          role: "क्लिनिकल रेडियोग्राफर",
          experience: "1 - 3 वर्ष",
          description: "ट्रॉमा, चेस्ट और जटिल हड्डियों के डिजिटल एक्स-रे स्वतंत्र रूप से संपन्न करना।"
        },
        {
          step: "03",
          role: "सीटी / एमआरआई स्पेशलिस्ट",
          experience: "3 - 6 वर्ष",
          description: "मल्टी-स्लाइस सीटी स्कैन, न्यूरो-एमआरआई और एंजियोग्राफी जैसी एडवांस्ड इमेजिंग करना।"
        },
        {
          step: "04",
          role: "चीफ रेडियोलॉजिकल टेक्नोलॉजिस्ट",
          experience: "6+ वर्ष",
          description: "पूरे रेडियोलॉजी विभाग का प्रबंधन, नई मशीनों की देखरेख और रेडिएशन सुरक्षा ऑडिट।"
        }
      ],
      skillsTitle: "प्रशिक्षण के दौरान अर्जित मुख्य कौशल",
      skills: [
        "डिजिटल एक्स-रे (DR & CR सिस्टम)",
        "सीटी स्कैन प्रोटोकॉल एवं स्लाइसिंग",
        "एमआरआई सुरक्षा एवं मैग्नेट प्रोटोकॉल",
        "रेडिएशन सुरक्षा एवं AERB नियम",
        "मानव शरीर रचना एवं पोजिशनिंग",
        "PACS एवं मेडिकल इमेज सॉफ्टवेयर",
        "इमरजेंसी ट्रॉमा इमेजिंग",
        "कंट्रास्ट स्टडीज असिस्टेंस"
      ],
      sectorsTitle: "प्रमुख रोजगार क्षेत्र",
      sectors: [
        {
          name: "मल्टी-स्पेशियलिटी अस्पताल व ट्रॉमा सेंटर",
          description: "24x7 इमरजेंसी एक्स-रे, आईसीयू बेडसाइड स्कैनिंग और ओटी में सी-आर्म (C-Arm) असिस्टेंस।"
        },
        {
          name: "एडवांस्ड डायग्नोस्टिक एवं स्कैनिंग सेंटर्स",
          description: "समर्पित सीटी, एमआरआई और डिजिटल एक्स-रे डायग्नोस्टिक चेन्स।"
        },
        {
          name: "कैंसर एवं ऑन्कोलॉजी हॉस्पिटल्स",
          description: "ट्यूमर इमेजिंग, पीईटी-सीटी और रेडिएशन थेरेपी सपोर्ट।"
        },
        {
          name: "ऑर्थोपेडिक व स्पोर्ट्स इंजरी क्लिनिक्स",
          description: "जोड़ों और हड्डियों के फ्रैक्चर की त्वरित जांच।"
        }
      ],
      relatedCoursesTitle: "इस करियर के लिए बोर्ड से जुड़े कोर्सेज",
      relatedCourses: [
        {
          code: "DRT",
          title: "डिप्लोमा इन रेडियोग्राफी टेक्नोलॉजी (X-Ray/CT)",
          duration: "2 वर्ष",
          eligibility: "10+2 (साइंस / PCB)",
          href: "/courses"
        },
        {
          code: "CXRT",
          title: "सर्टिफिकेट इन एक्स-रे तकनीशियन",
          duration: "1 वर्ष",
          eligibility: "10वीं / 10+2 उत्तीर्ण",
          href: "/courses"
        }
      ],
      ctaTitle: "क्या आप मेडिकल इमेजिंग व रेडियोग्राफी में अपना भविष्य बनाना चाहते हैं?",
      ctaDescription: "इंडियन पैरामेडिकल बोर्ड ऑफ इंडिया के मान्यता प्राप्त संस्थानों में प्रैक्टिकल ट्रेनिंग के साथ एडमिशन लें।",
      ctaButtonText: "कोर्सेज देखें एवं आवेदन करें"
    }
  },
  {
    id: 3,
    slug: "physiotherapist",
    image: "/Meditech3.jpeg",
    stats: {
      durationEn: "2 - 3.5 Years",
      durationHi: "2 से 3.5 वर्ष",
      eligibilityEn: "10+2 with PCB (Physics, Chem, Bio)",
      eligibilityHi: "10+2 (फिजिक्स, केमिस्ट्री, बायोलॉजी)",
      salaryEn: "₹25,000 - ₹60,000 / mo",
      salaryHi: "₹25,000 - ₹60,000 प्रति माह",
      demandEn: "High Demand",
      demandSubEn: "Rehab & Sports Clinics",
      demandHi: "उच्च मांग",
      demandSubHi: "रिहैब व स्पोर्ट्स क्लिनिक्स",
    },
    en: {
      title: "Physiotherapist & Rehabilitation Specialist",
      tagline: "Restoring Mobility, Relieving Pain, and Empowering Active Human Lives",
      badge: "Physical Rehabilitation & Wellness",
      aboutTitle: "About the Physiotherapy Profession",
      aboutParagraphs: [
        "Physiotherapy is a vital healthcare discipline focused on the assessment, maintenance, and restoration of physical movement, neuromuscular function, and musculoskeletal health.",
        "Physiotherapists work with stroke survivors, athletes suffering sports injuries, patients recovering from orthopedic surgeries (joint replacements, fractures), and elderly individuals managing arthritis and spinal disorders without drug dependency."
      ],
      rolesTitle: "Key Roles & Responsibilities",
      rolesDescription: "Essential therapeutic interventions carried out by physiotherapy professionals:",
      roles: [
        {
          title: "Functional & Mobility Assessment",
          description: "Evaluate patient posture, joint range of motion (ROM), muscle strength, and gait balance."
        },
        {
          title: "Designing Rehabilitation Regimens",
          description: "Formulate customized recovery exercises targeting pain reduction and muscular strengthening."
        },
        {
          title: "Electrotherapy & Modal Treatment",
          description: "Apply ultrasound therapy, TENS, IFT, traction, and laser therapy to alleviate soft-tissue inflammation."
        },
        {
          title: "Manual Therapy & Mobilization",
          description: "Perform skilled passive joint mobilization, myofascial release, and spinal adjustments."
        },
        {
          title: "Neuro-Rehabilitation",
          description: "Re-train stroke, Parkinson's, and spinal cord injury patients to regain functional independence."
        },
        {
          title: "Ergonomic & Postural Counseling",
          description: "Educate corporate professionals and factory workers on spinal mechanics and workplace ergonomics."
        }
      ],
      ladderTitle: "Career Progression Pathway",
      ladderSteps: [
        {
          step: "01",
          role: "Clinical Physiotherapy Assistant",
          experience: "0 - 1 Year",
          description: "Assisting patients with electrotherapy apparatus, warm-ups, and gym rehabilitation equipment."
        },
        {
          step: "02",
          role: "Consultant Physiotherapist",
          experience: "1 - 3 Years",
          description: "Conducting independent patient diagnoses, designing therapy regimes, and monitoring recovery."
        },
        {
          step: "03",
          role: "Senior Rehab / Sports Specialist",
          experience: "3 - 6 Years",
          description: "Specializing in sports injury biomechanics, ICU chest physiotherapy, or pediatric neuro-care."
        },
        {
          step: "04",
          role: "Head of Physiotherapy / Clinic Owner",
          experience: "6+ Years",
          description: "Directing hospital physical medicine departments or operating an independent rehabilitation clinic."
        }
      ],
      skillsTitle: "Key Technical & Clinical Skills Acquired",
      skills: [
        "Musculoskeletal & Joint Assessment",
        "Electrotherapy (TENS, IFT, Ultrasound)",
        "Post-Surgical Orthopedic Rehab",
        "Sports Kinesiology & Taping",
        "Neurological Stroke Recovery",
        "Chest & Cardiopulmonary Therapy",
        "Gait Training & Ergonomics",
        "Patient Counseling & Motivation"
      ],
      sectorsTitle: "Top Employment Sectors",
      sectors: [
        {
          name: "Orthopedic & Multi-Specialty Hospitals",
          description: "Inpatient post-operative recovery, joint replacement, and ICU chest care."
        },
        {
          name: "Sports Academies & Athletic Clubs",
          description: "Injury prevention, acute pitch-side management, and athletic conditioning."
        },
        {
          name: "Geriatric & Elderly Care Facilities",
          description: "Fall prevention, arthritis management, and mobility preservation in senior living."
        },
        {
          name: "Independent Physiotherapy & Rehab Clinics",
          description: "Private practice offering customized outpatient pain relief therapy."
        }
      ],
      relatedCoursesTitle: "Board Certified Courses for this Career",
      relatedCourses: [
        {
          code: "DPT",
          title: "Diploma in Physiotherapy",
          duration: "2 Years",
          eligibility: "10+2 with Science (PCB)",
          href: "/courses"
        },
        {
          code: "CPT",
          title: "Certificate in Physiotherapy Assistant",
          duration: "1 Year",
          eligibility: "10th / 10+2 Pass",
          href: "/courses"
        }
      ],
      ctaTitle: "Embark on a Rewarding Career Restoring Human Mobility",
      ctaDescription: "Enrol in board-recognized physiotherapy and rehabilitation programs with hands-on clinical internships.",
      ctaButtonText: "Explore Courses & Apply"
    },
    hi: {
      title: "फिजियोथेरेपिस्ट एवं रिहैबिलिटेशन विशेषज्ञ",
      tagline: "शारीरिक गतिशीलता की पुनर्स्थापना, दर्द से मुक्ति और स्वस्थ जीवन का आधार",
      badge: "शारीरिक पुनर्वास एवं स्वास्थ्य विशेषज्ञता",
      aboutTitle: "फिजियोथेरेपी करियर का परिचय",
      aboutParagraphs: [
        "फिजियोथेरेपी आधुनिक चिकित्सा की वह शाखा है जो बिना दवा या सर्जरी के प्राकृतिक व्यायाम, इलेक्ट्रोथेरेपी और हस्त-चिकित्सा (Manual Therapy) के जरिए शरीर के अंगों की गतिशीलता और कार्यक्षमता को वापस लाती है।",
        "हड्डियों के ऑपरेशन (जैसे घुटना या कूल्हा प्रत्यारोपण) के बाद मरीजों की रिकवरी, लकवा (पैरालिसिस) या स्ट्रोक के बाद चलने-फिरने की क्षमता लौटाने और खेल में लगी चोटों (Sports Injuries) को ठीक करने में फिजियोथेरेपिस्ट की भूमिका अपरिहार्य है।"
      ],
      rolesTitle: "मुख्य कार्य एवं जिम्मेदारियाँ",
      rolesDescription: "फिजियोथेरेपिस्ट द्वारा दैनिक रूप से किए जाने वाले प्रमुख चिकित्सीय कार्य:",
      roles: [
        {
          title: "शारीरिक जांच एवं गतिशीलता परीक्षण",
          description: "मरीज के जोड़ों के लचीलेपन, मांसपेशियों की ताकत, दर्द के स्तर और चलने के तरीके (Gait) की गहन जांच करना।"
        },
        {
          title: "पुनर्वास व्यायाम योजना तैयार करना",
          description: "प्रत्येक मरीज की चोट या स्थिति के अनुसार अनुकूलित (Customized) एक्सरसाइज प्लान बनाना।"
        },
        {
          title: "इलेक्ट्रोथेरेपी उपकरणों का प्रयोग",
          description: "दर्द और सूजन कम करने के लिए अल्ट्रासाउंड थेरेपी, TENS, IFT और हीट थेरेपी का सुरक्षित उपयोग करना।"
        },
        {
          title: "हस्त-चिकित्सा (Manual Therapy)",
          description: "हाथों से मांसपेशियों की जकड़न खोलना, जोड़ों को मोबिलाइज करना और रीढ़ की हड्डी के तनाव को दूर करना।"
        },
        {
          title: "न्यूरो-रिहैबिलिटेशन (लकवा उपचार)",
          description: "स्ट्रोक या ब्रेन इंजरी से प्रभावित मरीजों को दोबारा खड़े होने, चलने और रोजमर्रा के काम करने में सक्षम बनाना।"
        },
        {
          title: "पोस्चर एवं एर्गोनॉमिक्स परामर्श",
          description: "कंप्यूटर पर काम करने वालों और बुजुर्गों को कमर व गर्दन दर्द से बचने के सही उठने-बैठने के तरीकों की ट्रेनिंग देना।"
        }
      ],
      ladderTitle: "करियर में पदोन्नति एवं विकास क्रम",
      ladderSteps: [
        {
          step: "01",
          role: "क्लिनिकल असिस्टेंट फिजियोथेरेपिस्ट",
          experience: "0 - 1 वर्ष",
          description: "वरिष्ठ फिजियोथेरेपिस्ट के मार्गदर्शन में उपकरणों का संचालन और बेसिक स्ट्रेचिंग कराना।"
        },
        {
          step: "02",
          role: "कंसल्टेंट फिजियोथेरेपिस्ट",
          experience: "1 - 3 वर्ष",
          description: "स्वतंत्र रूप से मरीजों की जांच, थेरेपी सेशंस का संचालन और रिकवरी प्रोग्रेस मॉनिटर करना।"
        },
        {
          step: "03",
          role: "सीनियर रिहैब / स्पोर्ट्स स्पेशलिस्ट",
          experience: "3 - 6 वर्ष",
          description: "स्पोर्ट्स इंजरी, आईसीयू चेस्ट फिजियोथेरेपी या बाल रोग न्यूरो-केयर में विशेषज्ञता हासिल करना।"
        },
        {
          step: "04",
          role: "विभागाध्यक्ष / निजी क्लिनिक संचालक",
          experience: "6+ वर्ष",
          description: "अस्पताल के फिजियोथेरेपी विभाग का नेतृत्व करना या अपना सफल निजी रिहैबिलिटेशन सेंटर चलाना।"
        }
      ],
      skillsTitle: "प्रशिक्षण के दौरान अर्जित मुख्य कौशल",
      skills: [
        "मांसपेशी व जोड़ों की बायोमैकेनिक्स",
        "इलेक्ट्रोथेरेपी (TENS, IFT, अल्ट्रासाउंड)",
        "ऑर्थोपेडिक पोस्ट-सर्जरी रिहैब",
        "स्पोर्ट्स इंजरी मैनेजमेंट एवं टेपिंग",
        "न्यूरोलॉजिकल स्ट्रोक रिकवरी",
        "चेस्ट एवं कार्डियोपल्मोनरी थेरेपी",
        "एर्गोनॉमिक्स एवं लाइफस्टाइल काउंसलिंग",
        "मरीज संवाद एवं मानसिक संबल"
      ],
      sectorsTitle: "प्रमुख रोजगार क्षेत्र",
      sectors: [
        {
          name: "ऑर्थोपेडिक व मल्टी-स्पेशियलिटी अस्पताल",
          description: "ऑपरेशन के बाद इनडोर मरीजों की रिकवरी और आईसीयू पेशेंट्स की फिजियोथेरेपी।"
        },
        {
          name: "स्पोर्ट्स एकेडमी एवं फिटनेस क्लब्स",
          description: "खिलाड़ियों की चोट की रोकथाम, फील्ड-साइड फर्स्ट एड और फिटनेस कंडीशनिंग।"
        },
        {
          name: "बुजुर्ग देखभाल केंद्र (Geriatric Centers)",
          description: "बुजुर्गों में आर्थराइटिस का प्रबंधन और चलने-फिरने में संतुलन बनाए रखने की थेरेपी।"
        },
        {
          name: "निजी फिजियोथेरेपी क्लिनिक्स",
          description: "अपना स्वयं का रिहैबिलिटेशन सेंटर शुरू करने का उत्कृष्ट अवसर।"
        }
      ],
      relatedCoursesTitle: "इस करियर के लिए बोर्ड से जुड़े कोर्सेज",
      relatedCourses: [
        {
          code: "DPT",
          title: "डिप्लोमा इन फिजियोथेरेपी",
          duration: "2 वर्ष",
          eligibility: "10+2 (साइंस / PCB)",
          href: "/courses"
        },
        {
          code: "CPT",
          title: "सर्टिफिकेट इन फिजियोथेरेपी असिस्टेंट",
          duration: "1 वर्ष",
          eligibility: "10वीं / 10+2 उत्तीर्ण",
          href: "/courses"
        }
      ],
      ctaTitle: "क्या आप फिजियोथेरेपी में एक सम्मानजनक करियर बनाना चाहते हैं?",
      ctaDescription: "इंडियन पैरामेडिकल बोर्ड ऑफ इंडिया के संबद्ध संस्थानों से व्यावहारिक प्रशिक्षण के साथ डिप्लोमा कोर्स करें।",
      ctaButtonText: "कोर्सेज देखें एवं आवेदन करें"
    }
  },
  {
    id: 4,
    slug: "operation-theatre-tech",
    image: "/Meditech4.jpeg",
    stats: {
      durationEn: "1 - 2 Years",
      durationHi: "1 से 2 वर्ष",
      eligibilityEn: "10th / 10+2 (Science Preferred)",
      eligibilityHi: "10वीं / 10+2 (साइंस वरीयता)",
      salaryEn: "₹20,000 - ₹52,000 / mo",
      salaryHi: "₹20,000 - ₹52,000 प्रति माह",
      demandEn: "Critical Demand",
      demandSubEn: "Surgical Theatres & ICUs",
      demandHi: "अत्यंत आवश्यक",
      demandSubHi: "सर्जिकल ओटी व आईसीयू",
    },
    en: {
      title: "Operation Theatre Technician (OTT)",
      tagline: "The Guardian of Sterile Surgical Theatres and Critical Intra-Operative Support",
      badge: "Critical Surgical Care Specialization",
      aboutTitle: "About the Operation Theatre Technology Career",
      aboutParagraphs: [
        "Operation Theatre Technicians (OTT) are indispensable members of surgical teams. Before a surgeon makes the first incision, the OT Technician ensures that every surgical tool, anesthesia workstation, suction line, and cautery machine is flawlessly functioning, calibrated, and completely sterilized.",
        "During surgery, OT Technicians assist surgeons and anesthesiologists with instrument handling, vital monitoring, emergency medication supplies, and maintaining absolute asepsis to prevent life-threatening hospital-acquired surgical infections."
      ],
      rolesTitle: "Key Roles & Responsibilities",
      rolesDescription: "Vital intra-operative duties performed in surgical hospital wards:",
      roles: [
        {
          title: "Theatre Sterilization & Aseptic Protocols",
          description: "Disinfect surgical rooms, fumigate OT suites, and manage autoclave and ethylene oxide (ETO) sterilizers."
        },
        {
          title: "Surgical Table & Instrument Layout",
          description: "Arrange specialized surgical trays, retractors, scalpel blades, and sutures based on the planned operation."
        },
        {
          title: "Anesthesia Workstation Monitoring",
          description: "Check oxygen pipelines, nitrous oxide cylinders, vaporizers, and ventilator circuits with anesthesiologists."
        },
        {
          title: "Assisting Operating Surgeons",
          description: "Pass sterile instruments, hold retractors, adjust OT surgical lights, and manage electrosurgical cautery units."
        },
        {
          title: "Intra-Operative Specimen Handling",
          description: "Safely preserve biopsies, resected tissues, and excised lesions for pathological examination."
        },
        {
          title: "Post-Operative Patient Transfer",
          description: "Safely disconnect surgical monitoring leads and transfer recovering patients to the Post-Anesthesia Care Unit (PACU)."
        }
      ],
      ladderTitle: "Career Progression Pathway",
      ladderSteps: [
        {
          step: "01",
          role: "Trainee OT Assistant",
          experience: "0 - 1 Year",
          description: "Learning theatre fumigation, instrument packing, autoclave cycles, and gowning/gloving."
        },
        {
          step: "02",
          role: "Junior Scrub / Circulating Tech",
          experience: "1 - 3 Years",
          description: "Assisting in general surgical procedures, laparoscopic surgeries, and basic orthopedic fixations."
        },
        {
          step: "03",
          role: "Senior Surgical / Specialty Technologist",
          experience: "3 - 6 Years",
          description: "Handling high-risk neurosurgery, cardiac bypass, organ transplants, and robotic surgery suites."
        },
        {
          step: "04",
          role: "Chief OT Manager / Supervisor",
          experience: "6+ Years",
          description: "Directing multi-theatre scheduling, CSSD operations, surgical equipment inventory, and NABH compliance."
        }
      ],
      skillsTitle: "Key Technical & Clinical Skills Acquired",
      skills: [
        "Aseptic Technique & CSSD Autoclaving",
        "Anesthesia Workstation Setup",
        "Electrosurgical Cautery & Diathermy",
        "Laparoscopic Camera & Insufflator Handling",
        "Surgical Instrument Trolley Layout",
        "Patient Vital Signs Monitoring",
        "Biomedical Waste & Infection Control",
        "Emergency Resuscitation & BLS Support"
      ],
      sectorsTitle: "Top Employment Sectors",
      sectors: [
        {
          name: "Multi-Specialty & Super-Specialty Hospitals",
          description: "Handling cardiac, neuro, orthopedic, gastro, and pediatric surgical suites."
        },
        {
          name: "Dedicated Day-Care Surgery Centers",
          description: "Laparoscopic, ophthalmic, and cosmetic surgical procedure clinics."
        },
        {
          name: "Central Sterile Supply Departments (CSSD)",
          description: "Supervising hospital-wide instrument decontamination and sterile distribution."
        },
        {
          name: "Trauma & Emergency Resuscitation Units",
          description: "Emergency surgical laparotomies and acute trauma stabilization."
        }
      ],
      relatedCoursesTitle: "Board Certified Courses for this Career",
      relatedCourses: [
        {
          code: "DOTT",
          title: "Diploma in Operation Theatre Technology",
          duration: "2 Years",
          eligibility: "10+2 with Science (PCB)",
          href: "/courses"
        },
        {
          code: "COTT",
          title: "Certificate in Operation Theatre Technology",
          duration: "1 Year",
          eligibility: "10th / 10+2 Pass",
          href: "/courses"
        }
      ],
      ctaTitle: "Step Inside the Heart of Surgical Medicine",
      ctaDescription: "Join the critical frontline of operating theatres through certified diploma programs authorized by the Indian Paramedical Board of India.",
      ctaButtonText: "Explore Courses & Apply"
    },
    hi: {
      title: "ऑपरेशन थियेटर तकनीशियन (OTT)",
      tagline: "सर्जरी की सफलता और संक्रमण-मुक्त ऑपरेशन थियेटर के कुशल संरक्षक",
      badge: "महत्वपूर्ण सर्जिकल केयर विशेषज्ञता",
      aboutTitle: "ऑपरेशन थियेटर टेक्नोलॉजी करियर का परिचय",
      aboutParagraphs: [
        "ऑपरेशन थियेटर तकनीशियन (OTT) सर्जिकल टीम का अत्यंत महत्वपूर्ण अंग होते हैं। जब एक सर्जन ऑपरेशन शुरू करता है, उससे पहले ओटी तकनीशियन यह सुनिश्चित करता है कि हर सर्जिकल औजार, एनेस्थीसिया मशीन, सक्शन पाइपलाइन और कॉटरी मशीन पूरी तरह से स्वच्छ, रोगाणुमुक्त (Sterilized) और चालू स्थिति में हो।",
        "ऑपरेशन के दौरान ओटी तकनीशियन सर्जन को सही समय पर उपकरण सौंपते हैं, मरीज के वाइटल्स पर नजर रखते हैं और किसी भी प्रकार के जानलेवा संक्रमण (Infection) को रोकने के लिए ऑपरेशन थियेटर में कड़े नियमों का पालन करवाते हैं।"
      ],
      rolesTitle: "मुख्य कार्य एवं जिम्मेदारियाँ",
      rolesDescription: "ऑपरेशन थियेटर में प्रतिदिन निभाए जाने वाले आवश्यक सर्जिकल कर्तव्य:",
      roles: [
        {
          title: "थियेटर की नसबंदी व स्टेरलाइजेशन",
          description: "ऑटोक्लेव और ETO मशीनों द्वारा सर्जिकल औजारों को रोगाणुमुक्त करना और ओटी की नियमित फ्यूमिगेशन करना।"
        },
        {
          title: "सर्जिकल ट्रॉली व औजारों की तैयारी",
          description: "होने वाले ऑपरेशन के अनुसार स्कैल्पल, संदंश (Forceps), कैंची और टांके (Sutures) को क्रमबद्ध तरीके से सजाना।"
        },
        {
          title: "एनेस्थीसिया उपकरण की जांच",
          description: "एनेस्थीसिया डॉक्टर के साथ ऑक्सीजन सिलेंडर, वेपोराइजर और वेंटिलेटर सर्किट की पूरी जांच करना।"
        },
        {
          title: "सर्जन को ऑपरेशन में सहायता (Scrubbing)",
          description: "ऑपरेशन के समय सर्जन को सही औजार पकड़ाना, लाइट एडजस्ट करना और इलेक्ट्रिकल कॉटरी मशीन संभालना।"
        },
        {
          title: "बायोप्सी और सैंपल सुरक्षित करना",
          description: "ऑपरेशन में निकाले गए ऊतकों (बायोप्सी) को सही तरल में सुरक्षित करके जांच के लिए पैथोलॉजी लैब भेजना।"
        },
        {
          title: "ऑपरेशन के बाद मरीज की देखभाल",
          description: "ऑपरेशन पूरा होने के बाद मरीज को सुरक्षित रूप से रिकवरी रूम (PACU) या आईसीयू में शिफ्ट कराना।"
        }
      ],
      ladderTitle: "करियर में पदोन्नति एवं विकास क्रम",
      ladderSteps: [
        {
          step: "01",
          role: "ट्रेनी ओटी असिस्टेंट",
          experience: "0 - 1 वर्ष",
          description: "ओटी स्टेरलाइजेशन, गाउनिंग-ग्लविंग तकनीक, औजारों की धुलाई और ऑटोक्लेव चलाना सीखना।"
        },
        {
          step: "02",
          role: "स्क्रब / सर्कुलेटिंग तकनीशियन",
          experience: "1 - 3 वर्ष",
          description: "सामान्य सर्जरी, लैप्रोस्कोपिक सर्जरी और हड्डी के ऑपरेशनों में सर्जन की सहायता करना।"
        },
        {
          step: "03",
          role: "सीनियर सर्जिकल टेक्नोलॉजिस्ट",
          experience: "3 - 6 वर्ष",
          description: "हार्ट सर्जरी (कार्डियक), न्यूरोसर्जरी और ऑर्गन ट्रांसप्लांट जैसे जटिल ऑपरेशनों को संभालना।"
        },
        {
          step: "04",
          role: "ओटी मैनेजर / सुपरवाइजर",
          experience: "6+ वर्ष",
          description: "सभी ऑपरेशन थियेटर्स का शेड्यूल, सीएसएसडी (CSSD) विभाग और NABH मानकों का संपूर्ण प्रबंधन।"
        }
      ],
      skillsTitle: "प्रशिक्षण के दौरान अर्जित मुख्य कौशल",
      skills: [
        "एसेप्टिक तकनीक एवं सीएसएसडी ऑटोक्लेविंग",
        "एनेस्थीसिया वर्कस्टेशन व मॉनिटरिंग",
        "इलेक्ट्रोसर्जिकल कॉटरी का सुरक्षित उपयोग",
        "लैप्रोस्कोपिक कैमरा व सर्जिकल उपकरण",
        "सर्जिकल इंस्ट्रूमेंट ट्रॉली सेटअप",
        "मरीज के महत्वपूर्ण संकेतों की निगरानी",
        "अस्पताल संक्रमण नियंत्रण (NABH)",
        "इमरजेंसी सीपीआर व बीएलएस सपोर्ट"
      ],
      sectorsTitle: "प्रमुख रोजगार क्षेत्र",
      sectors: [
        {
          name: "मल्टी-स्पेशियलिटी अस्पताल",
          description: "कार्डियक, न्यूरो, ऑर्थोपेडिक, और पीडियाट्रिक ऑपरेशन थियेटर यूनिट्स।"
        },
        {
          name: "डे-केयर सर्जरी क्लिनिक्स",
          description: "लैप्रोस्कोपी, नेत्र सर्जरी और कॉस्मेटिक सर्जरी सेंटर्स।"
        },
        {
          name: "सेंट्रल स्टाइल सप्लाई डिपार्टमेंट (CSSD)",
          description: "अस्पताल भर के सर्जिकल औजारों की नसबंदी और वितरण का मुख्य केंद्र।"
        },
        {
          name: "इमरजेंसी एवं ट्रॉमा केयर सेंटर्स",
          description: "आपातकालीन दुर्घटनाओं और जीवन रक्षक त्वरित सर्जरी में योगदान।"
        }
      ],
      relatedCoursesTitle: "इस करियर के लिए बोर्ड से जुड़े कोर्सेज",
      relatedCourses: [
        {
          code: "DOTT",
          title: "डिप्लोमा इन ऑपरेशन थियेटर टेक्नोलॉजी",
          duration: "2 वर्ष",
          eligibility: "10+2 (साइंस / PCB)",
          href: "/courses"
        },
        {
          code: "COTT",
          title: "सर्टिफिकेट इन ऑपरेशन थियेटर टेक्नोलॉजी",
          duration: "1 वर्ष",
          eligibility: "10वीं / 10+2 उत्तीर्ण",
          href: "/courses"
        }
      ],
      ctaTitle: "क्या आप सर्जिकल हेल्थकेयर के क्षेत्र में अपना भविष्य बनाना चाहते हैं?",
      ctaDescription: "इंडियन पैरामेडिकल बोर्ड ऑफ इंडिया के संबद्ध संस्थानों से मान्यता प्राप्त डिप्लोमा या सर्टिफिकेट कोर्स में प्रवेश लें।",
      ctaButtonText: "कोर्सेज देखें एवं आवेदन करें"
    }
  },
  {
    id: 5,
    slug: "dental-hygienist",
    image: "/Meditech5.jpeg",
    stats: {
      durationEn: "1 - 2 Years",
      durationHi: "1 से 2 वर्ष",
      eligibilityEn: "10+2 (Science Preferred) / 10th",
      eligibilityHi: "10+2 (साइंस वरीयता) / 10वीं",
      salaryEn: "₹18,000 - ₹45,000 / mo",
      salaryHi: "₹18,000 - ₹45,000 प्रति माह",
      demandEn: "Rapidly Growing",
      demandSubEn: "Cosmetic & Dental Clinics",
      demandHi: "तेजी से बढ़ती मांग",
      demandSubHi: "डेंटल व ओरल केयर क्लिनिक्स",
    },
    en: {
      title: "Dental Hygienist & Oral Healthcare Specialist",
      tagline: "Championing Preventive Dentistry, Ultrasonic Scaling, and Radiant Oral Health",
      badge: "Dental Healthcare & Hygiene",
      aboutTitle: "About the Dental Hygiene Profession",
      aboutParagraphs: [
        "Dental Hygienists are registered allied dental professionals specializing in preventive oral care, periodontal screening, ultrasonic dental scaling, and patient oral health education.",
        "They work alongside dentists and oral maxillofacial surgeons, conducting routine teeth cleanings, applying fluorides and pit-and-fissure sealants, capturing dental intra-oral radiographs, and helping patients avert gum disease, plaque buildup, and tooth decay."
      ],
      rolesTitle: "Key Roles & Responsibilities",
      rolesDescription: "Essential clinical procedures conducted in modern dental operatories:",
      roles: [
        {
          title: "Ultrasonic Scaling & Polishing",
          description: "Remove supragingival and subgingival calculus, stubborn stains, and plaque biofilm using ultrasonic scalers."
        },
        {
          title: "Periodontal Screening & Charting",
          description: "Measure periodontal pocket depths, assess gingival bleeding, and record dental health indices."
        },
        {
          title: "Dental Radiography (IOPA & OPG)",
          description: "Position dental X-ray film/sensors to capture intra-oral periapical and panoramic jaw radiographs."
        },
        {
          title: "Preventive Fluoride & Sealant Therapy",
          description: "Apply topical fluorides, desensitizing agents, and resin-based sealants on deep occlusal grooves."
        },
        {
          title: "Chairside Assisting & Impression Taking",
          description: "Assist dentists during crown preparations, root canals, and pour accurate diagnostic plaster casts."
        },
        {
          title: "Patient Preventive Education",
          description: "Educate adults and children on modified Bass brushing methods, flossing, and dietary sugar regulation."
        }
      ],
      ladderTitle: "Career Progression Pathway",
      ladderSteps: [
        {
          step: "01",
          role: "Trainee Dental Assistant",
          experience: "0 - 1 Year",
          description: "Sterilizing dental handpieces, preparing impression materials, and managing chairside suction."
        },
        {
          step: "02",
          role: "Registered Dental Hygienist",
          experience: "1 - 3 Years",
          description: "Independent execution of ultrasonic scalings, deep root planings, and fluoride applications."
        },
        {
          step: "03",
          role: "Senior Dental Clinical Coordinator",
          experience: "3 - 6 Years",
          description: "Overseeing dental clinic sterilization, inventory management, cosmetic whitening, and staff training."
        },
        {
          step: "04",
          role: "Dental Practice Manager",
          experience: "6+ Years",
          description: "Directing multi-chair dental operations, aesthetic smile clinics, and community dental outreach camps."
        }
      ],
      skillsTitle: "Key Technical & Clinical Skills Acquired",
      skills: [
        "Ultrasonic & Manual Dental Scaling",
        "Intra-Oral Dental X-Ray (RVG & IOPA)",
        "Gingival Health & Periodontal Charting",
        "Dental Autoclave & Cross-Infection Control",
        "Topical Fluoride & Sealant Application",
        "Alginate Impressions & Model Pouring",
        "Four-Handed Chairside Assisting",
        "Oral Hygiene Patient Motivation"
      ],
      sectorsTitle: "Top Employment Sectors",
      sectors: [
        {
          name: "Private Dental Clinics & Polyclinics",
          description: "Routine oral cleaning, teeth polishing, and cosmetic dental assistance."
        },
        {
          name: "Hospital Dental Departments",
          description: "Pre-cardiac surgery oral cleanings and trauma maxillofacial care."
        },
        {
          name: "Corporate Dental Chains",
          description: "High-volume preventive checkups and branded dental retail networks."
        },
        {
          name: "Community Health & School Outreach Programs",
          description: "Rural oral hygiene screening and preventive fluoride camps."
        }
      ],
      relatedCoursesTitle: "Board Certified Courses for this Career",
      relatedCourses: [
        {
          code: "DDH",
          title: "Diploma in Dental Hygienist",
          duration: "2 Years",
          eligibility: "10+2 with Science (PCB)",
          href: "/courses"
        },
        {
          code: "CDA",
          title: "Certificate in Dental Assistant & Hygiene",
          duration: "1 Year",
          eligibility: "10th / 10+2 Pass",
          href: "/courses"
        }
      ],
      ctaTitle: "Bring Healthy Smiles to Life as a Dental Hygienist",
      ctaDescription: "Enrol in recognized dental hygiene programs designed to equip you with modern ultrasonic and diagnostic skills.",
      ctaButtonText: "Explore Courses & Apply"
    },
    hi: {
      title: "डेंटल हाइजीनिस्ट एवं ओरल हेल्थकेयर विशेषज्ञ",
      tagline: "दांतों की सुरक्षा, पायरिया की रोकथाम और स्वस्थ मुस्कान का सच्चा रक्षक",
      badge: "दंत चिकित्सा एवं स्वच्छता विशेषज्ञता",
      aboutTitle: "डेंटल हाइजीन करियर का परिचय",
      aboutParagraphs: [
        "डेंटल हाइजीनिस्ट दंत चिकित्सा (Dentistry) के क्षेत्र में प्रशिक्षित स्वास्थ्य पेशेवर होते हैं, जिनका मुख्य कार्य दांतों और मसूड़ों को बीमारियों से बचाना, दांतों पर जमी गंदगी (टार्टर/प्लाक) को अल्ट्रासोनिक स्केलिंग से साफ करना और मरीजों को मुंह की स्वच्छता की सही जानकारी देना है।",
        "वे डेंटिस्ट (दंत चिकित्सक) के साथ मिलकर काम करते हैं। दांतों की नियमित सफाई, दांतों के एक्स-रे (RVG/IOPA) लेना, मसूड़ों से खून आने (Gingivitis) का इलाज करना और ओरल हाइजीन कैंप्स का संचालन करना इनकी प्रमुख जिम्मेदारियां हैं।"
      ],
      rolesTitle: "मुख्य कार्य एवं जिम्मेदारियाँ",
      rolesDescription: "डेंटल क्लिनिक में प्रतिदिन किए जाने वाले आवश्यक कार्य:",
      roles: [
        {
          title: "अल्ट्रासोनिक स्केलिंग व पॉलिशिंग",
          description: "आधुनिक अल्ट्रासोनिक मशीनों से दांतों पर जमी सख्त पपड़ी (कैलकुलस), दाग-धब्बे और टार्टर को सुरक्षित रूप से साफ करना।"
        },
        {
          title: "मसूड़ों की जांच (Periodontal Screening)",
          description: "मसूड़ों की गहराई और खून आने की समस्या की जांच करना और मसूड़ों की स्थिति का चार्ट तैयार करना।"
        },
        {
          title: "दांतों का एक्स-रे लेना (Dental X-Ray)",
          description: "डिजिटल आरवीजी (RVG) या आईओपीए फिल्म के जरिए दांतों की जड़ों और कैविटी की सटीक तस्वीर खींचना।"
        },
        {
          title: "फ्लोराइड एवं सीलेंट ट्रीटमेंट",
          description: "बच्चों और वयस्कों के दांतों में कीड़ा लगने से बचाने के लिए फ्लोराइड जेल और डेंटल सीलेंट लगाना।"
        },
        {
          title: "डेंटिस्ट को चेयरसाइड सहायता",
          description: "रूट कैनाल (RCT), दांत निकालने और कैप लगाने के दौरान डेंटिस्ट को सही औजार पकड़ाना और सक्शन संभालना।"
        },
        {
          title: "मरीजों को ब्रश करने का सही तरीका सिखाना",
          description: "दांतों को लंबे समय तक मजबूत रखने के लिए ब्रश करने, फ्लॉसिंग करने और खानपान की सही आदतों की ट्रेनिंग देना।"
        }
      ],
      ladderTitle: "करियर में पदोन्नति एवं विकास क्रम",
      ladderSteps: [
        {
          step: "01",
          role: "ट्रेनी डेंटल असिस्टेंट",
          experience: "0 - 1 वर्ष",
          description: "डेंटल उपकरणों का स्टेरलाइजेशन, इंप्रेशन मैटेरियल तैयार करना और चेयरसाइड सहायता।"
        },
        {
          step: "02",
          role: "रजिस्टर्ड डेंटल हाइजीनिस्ट",
          experience: "1 - 3 वर्ष",
          description: "स्वतंत्र रूप से अल्ट्रासोनिक स्केलिंग, टीथ पॉलिशिंग और डेंटल एक्स-रे का संचालन।"
        },
        {
          step: "03",
          role: "सीनियर क्लिनिकल कोऑर्डिनेटर",
          experience: "3 - 6 वर्ष",
          description: "क्लिनिक संक्रमण नियंत्रण, टीथ व्हाइटनिंग, नए कर्मचारियों का प्रशिक्षण और पेशेंट केयर।"
        },
        {
          step: "04",
          role: "डेंटल क्लिनिक मैनेजर / प्रैक्टिस हेड",
          experience: "6+ वर्ष",
          description: "मल्टी-चेयर डेंटल सेंटर का संपूर्ण प्रबंधन, कॉस्मेटिक डेंटल सर्विसेज और ओरल हेल्थ कैंप्स।"
        }
      ],
      skillsTitle: "प्रशिक्षण के दौरान अर्जित मुख्य कौशल",
      skills: [
        "अल्ट्रासोनिक व मैन्युअल डेंटल स्केलिंग",
        "डिजिटल डेंटल एक्स-रे (RVG/IOPA)",
        "मसूड़ों की जांच एवं ओरल हेल्थ चार्टिंग",
        "डेंटल ऑटोक्लेव व संक्रमण रोकथाम",
        "टॉपिकल फ्लोराइड व सीलेंट एप्लीकेशन",
        "दांतों का नाप (इंप्रेशन) लेना व मॉडल बनाना",
        "फोर-हैंडेड चेयरसाइड असिस्टेंस",
        "ओरल हाइजीन पेशेंट काउंसलिंग"
      ],
      sectorsTitle: "प्रमुख रोजगार क्षेत्र",
      sectors: [
        {
          name: "निजी डेंटल क्लिनिक्स एवं पॉलीक्लिनिक्स",
          description: "नियमित दांतों की सफाई, पॉलिशिंग और दंत चिकित्सकों के साथ कार्य।"
        },
        {
          name: "अस्पतालों के डेंटल विभाग",
          description: "हॉस्पिटल इनपेशेंट्स और ऑपरेशनों से पहले ओरल कैविटी की सफाई।"
        },
        {
          name: "कॉर्पोरेट डेंटल चेन्स (Dental Chains)",
          description: "बड़े शहरों में तेजी से फैल रहे आधुनिक डेंटल क्लिनिक नेटवर्क्स।"
        },
        {
          name: "सामुदायिक स्वास्थ्य केंद्र एवं ओरल कैंप्स",
          description: "ग्रामीण और स्कूली बच्चों में दांतों की सुरक्षा के लिए आयोजित कैंप्स।"
        }
      ],
      relatedCoursesTitle: "इस करियर के लिए बोर्ड से जुड़े कोर्सेज",
      relatedCourses: [
        {
          code: "DDH",
          title: "डिप्लोमा इन डेंटल हाइजीनिस्ट",
          duration: "2 वर्ष",
          eligibility: "10+2 (साइंस / PCB)",
          href: "/courses"
        },
        {
          code: "CDA",
          title: "सर्टिफिकेट इन डेंटल असिस्टेंट एवं हाइजीन",
          duration: "1 वर्ष",
          eligibility: "10वीं / 10+2 उत्तीर्ण",
          href: "/courses"
        }
      ],
      ctaTitle: "क्या आप दंत चिकित्सा के क्षेत्र में एक आकर्षक करियर बनाना चाहते हैं?",
      ctaDescription: "इंडियन पैरामेडिकल बोर्ड ऑफ इंडिया के मान्यता प्राप्त संस्थानों से डेंटल हाइजीन कोर्स में प्रवेश लें।",
      ctaButtonText: "कोर्सेज देखें एवं आवेदन करें"
    }
  },
  {
    id: 6,
    slug: "optometrist",
    image: "/Meditech6.jpeg",
    stats: {
      durationEn: "2 - 3 Years",
      durationHi: "2 से 3 वर्ष",
      eligibilityEn: "10+2 with Science (PCB/PCM)",
      eligibilityHi: "10+2 (साइंस / PCB/PCM)",
      salaryEn: "₹22,000 - ₹55,000 / mo",
      salaryHi: "₹22,000 - ₹55,000 प्रति माह",
      demandEn: "High Demand",
      demandSubEn: "Eye Hospitals & Optical",
      demandHi: "उच्च मांग",
      demandSubHi: "नेत्र अस्पताल व रिटेल चेन्स",
    },
    en: {
      title: "Optometrist & Ophthalmic Assistant",
      tagline: "Preserving the Gift of Clear Vision through Precision Refraction and Eye Care",
      badge: "Vision Science & Ophthalmic Care",
      aboutTitle: "About the Optometry Profession",
      aboutParagraphs: [
        "Optometrists and Ophthalmic Technicians are healthcare professionals dedicated to examining human eyes, diagnosing refractive vision defects (myopia, hyperopia, astigmatism), and prescribing corrective eyeglasses and contact lenses.",
        "They work in close synergy with ophthalmologist eye surgeons, performing automated keratometry, non-contact tonometry (glaucoma screening), slit-lamp biomicroscopy, visual field testing, and pre-operative evaluation for cataract and LASIK laser surgeries."
      ],
      rolesTitle: "Key Roles & Responsibilities",
      rolesDescription: "Essential visual diagnostic procedures carried out in eye clinics:",
      roles: [
        {
          title: "Comprehensive Vision Testing & Refraction",
          description: "Perform objective retinoscopy and subjective manifest refraction with trial lens sets and phoropters."
        },
        {
          title: "Slit-Lamp Biomicroscopy",
          description: "Examine anterior segment structures of the eye including cornea, conjunctiva, iris, and crystalline lens."
        },
        {
          title: "Intraocular Pressure (IOP) Measurement",
          description: "Utilize non-contact or applanation tonometry to screen for early signs of glaucoma (kala motia)."
        },
        {
          title: "Contact Lens Fitting & Care Guidance",
          description: "Determine corneal curvature and fit soft, toric, or rigid gas-permeable contact lenses with hygiene instructions."
        },
        {
          title: "Pre-Surgical Ophthalmic Biometry",
          description: "Conduct A-scan ultrasound and optical biometry to compute intraocular lens (IOL) power before cataract surgery."
        },
        {
          title: "Visual Field & OCT Analysis",
          description: "Operate automated Humphrey visual field perimetry and optical coherence tomography (OCT) machines."
        }
      ],
      ladderTitle: "Career Progression Pathway",
      ladderSteps: [
        {
          step: "01",
          role: "Trainee Ophthalmic Assistant",
          experience: "0 - 1 Year",
          description: "Handling vision charts, auto-refractometers, lensometers, and eye drop administration."
        },
        {
          step: "02",
          role: "Clinical Optometrist",
          experience: "1 - 3 Years",
          description: "Conducting independent visual refractions, contact lens dispensing, and dry eye evaluations."
        },
        {
          step: "03",
          role: "Senior Consultant / Specialty Optometrist",
          experience: "3 - 6 Years",
          description: "Managing low-vision aids, pediatric vision therapy, keratoconus management, and surgical biometry."
        },
        {
          step: "04",
          role: "Chief of Optometry / Optical Center Owner",
          experience: "6+ Years",
          description: "Directing hospital eye clinics, optical franchise chains, or owning an independent vision care boutique."
        }
      ],
      skillsTitle: "Key Technical & Clinical Skills Acquired",
      skills: [
        "Subjective & Objective Refraction",
        "Slit-Lamp Anterior Segment Examination",
        "Tonometry & Glaucoma Screening",
        "Contact Lens Specialty Fitting",
        "Cataract A-Scan & IOL Power Calculation",
        "Automated Perimetry & OCT Scanning",
        "Pediatric Vision Screening",
        "Optical Dispensing & Lens Surfacing"
      ],
      sectorsTitle: "Top Employment Sectors",
      sectors: [
        {
          name: "Eye Hospitals & Ophthalmic Institutes",
          description: "Pre-cataract workups, glaucoma diagnostics, retina clinics, and surgical assisting."
        },
        {
          name: "National & Global Optical Retail Chains",
          description: "Retail vision checkups in chains like Lenskart, Titan Eyeplus, and Lawrence & Mayo."
        },
        {
          name: "LASIK & Refractive Surgery Centers",
          description: "Corneal topography and pre-laser vision correction screening."
        },
        {
          name: "Independent Optical & Vision Boutiques",
          description: "Starting your own independent eye testing center and optical dispensary."
        }
      ],
      relatedCoursesTitle: "Board Certified Courses for this Career",
      relatedCourses: [
        {
          code: "DOT",
          title: "Diploma in Optometry Technology",
          duration: "2 Years",
          eligibility: "10+2 with Science (PCB/PCM)",
          href: "/courses"
        },
        {
          code: "COT",
          title: "Certificate in Ophthalmic Technology",
          duration: "1 Year",
          eligibility: "10th / 10+2 Pass",
          href: "/courses"
        }
      ],
      ctaTitle: "Open Eyes to a Clearer World as an Optometrist",
      ctaDescription: "Enrol in board-certified optometry and ophthalmic technology courses with comprehensive clinical equipment training.",
      ctaButtonText: "Explore Courses & Apply"
    },
    hi: {
      title: "ऑप्टोमेट्रिस्ट एवं ऑप्थैल्मिक विशेषज्ञ",
      tagline: "सटीक नेत्र परीक्षण, चश्मे के नंबर निर्धारण और दृष्टि सुरक्षा का कुशल विज्ञान",
      badge: "दृष्टि विज्ञान एवं नेत्र देखभाल विशेषज्ञता",
      aboutTitle: "ऑप्टोमेट्री करियर का परिचय",
      aboutParagraphs: [
        "ऑप्टोमेट्रिस्ट और ऑप्थैल्मिक तकनीशियन आंखों की जांच करने, दूर और पास की नजर की कमजोरी (मायोपिया, हाइपरोपिया, एस्टिग्मैटिज्म) को पहचानने और सही नंबर का चश्मा या कॉन्टैक्ट लेंस देने वाले विशेषज्ञ होते हैं।",
        "वे आई-सर्जन (नेत्र विशेषज्ञ डॉक्टर) के साथ मिलकर काम करते हैं। मोतियाबिंद (Cataract) के ऑपरेशन से पहले आंख के लेंस का नंबर निकालना (A-Scan), काला मोतिया (Glaucoma) की जांच के लिए आंख का प्रेशर नापना और रेटिना व कॉर्निया की जांच में इनकी अहम भूमिका होती है।"
      ],
      rolesTitle: "मुख्य कार्य एवं जिम्मेदारियाँ",
      rolesDescription: "नेत्र क्लिनिक में प्रतिदिन किए जाने वाले आवश्यक कार्य:",
      roles: [
        {
          title: "सटीक नेत्र परीक्षण व चश्मे का नंबर",
          description: "ऑटो-रिफ्रेक्टोमीटर और ट्रायल फ्रेम की मदद से आंखों की नजर का सटीक नंबर निकालना।"
        },
        {
          title: "स्लिट-लैम्प माइक्रोस्कोप से जांच",
          description: "आंख की पुतली (कॉर्निया), परदे और लेंस की स्थिति की सूक्ष्मदर्शी से गहन जांच करना।"
        },
        {
          title: "आंख का दबाव नापना (Tonometry)",
          description: "काला मोतियाबिंद (Glaucoma) के शुरुआती लक्षणों की पहचान के लिए आंख का इंट्राओकुलर प्रेशर मापना।"
        },
        {
          title: "कॉन्टैक्ट लेंस फिटिंग व सलाह",
          description: "मरीजों की आंखों के आकार के अनुसार सॉफ्ट व गैस-परमिएबल कॉन्टैक्ट लेंस लगाना और रखरखाव सिखाना।"
        },
        {
          title: "मोतियाबिंद सर्जरी से पहले बायोमेट्री",
          description: "ए-स्कैन (A-Scan) अल्ट्रासाउंड द्वारा मोतियाबिंद ऑपरेशन के लिए सही पावर के लेंस (IOL) का चयन करना।"
        },
        {
          title: "विजुअल फील्ड व ओसीटी (OCT) टेस्ट",
          description: "नसों और रेटिना के रोगों की पहचान के लिए आधुनिक कंप्यूटराइज्ड ओसीटी मशीनों का संचालन करना।"
        }
      ],
      ladderTitle: "करियर में पदोन्नति एवं विकास क्रम",
      ladderSteps: [
        {
          step: "01",
          role: "ट्रेनी ऑप्थैल्मिक असिस्टेंट",
          experience: "0 - 1 वर्ष",
          description: "विजन चार्ट रीडिंग, ऑटो-रिफ्रैक्टर चलाना और आई ड्रॉप्स डालने का अभ्यास।"
        },
        {
          step: "02",
          role: "क्लिनिकल ऑप्टोमेट्रिस्ट",
          experience: "1 - 3 वर्ष",
          description: "स्वतंत्र रूप से आंखों का नंबर निकालना, कॉन्टैक्ट लेंस फिटिंग और ड्राई आई टेस्ट।"
        },
        {
          step: "03",
          role: "सीनियर कंसल्टेंट ऑप्टोमेट्रिस्ट",
          experience: "3 - 6 वर्ष",
          description: "लेसिक लेजर जांच, मोतियाबिंद बायोमेट्री और बच्चों के दृष्टि दोषों का इलाज।"
        },
        {
          step: "04",
          role: "चीफ ऑप्टोमेट्रिस्ट / ऑप्टिकल सेंटर मालिक",
          experience: "6+ वर्ष",
          description: "नेत्र अस्पताल के ऑप्टोमेट्री विभाग का नेतृत्व करना या अपना सफल ऑप्टिकल शोरूम चलाना।"
        }
      ],
      skillsTitle: "प्रशिक्षण के दौरान अर्जित मुख्य कौशल",
      skills: [
        "ऑब्जेक्टिव व सब्जेक्टिव रिफ्रैक्शन",
        "स्लिट-लैम्प द्वारा आंख की संरचना जांच",
        "टोनोमेट्री एवं काला मोतिया जांच",
        "कॉन्टैक्ट लेंस प्रिस्क्रिप्शन व फिटिंग",
        "मोतियाबिंद ए-स्कैन व आईओएल कैलकुलेशन",
        "कंप्यूटराइज्ड विजुअल फील्ड व ओसीटी",
        "बच्चों में दृष्टि दोष की पहचान",
        "ऑप्टिकल लेंस फिटिंग व डिस्पेंसिंग"
      ],
      sectorsTitle: "प्रमुख रोजगार क्षेत्र",
      sectors: [
        {
          name: "नेत्र अस्पताल एवं आई-केयर सेंटर्स",
          description: "मोतियाबिंद, ग्लूकोमा, रेटिना और लेसिक जांच विभागों में उच्च पद।"
        },
        {
          name: "राष्ट्रीय व बहुराष्ट्रीय ऑप्टिकल चेन्स",
          description: "लेंसकार्ट (Lenskart), टाइटन आईप्लस (Titan Eyeplus) जैसे रिटेल स्टोर्स में कंसल्टेंट।"
        },
        {
          name: "लेसिक व रिफ्रैक्टिव लेजर सेंटर्स",
          description: "चश्मा हटाने वाले लेजर ऑपरेशनों से पहले कॉर्नियल स्कैनिंग का कार्य।"
        },
        {
          name: "स्वतंत्र ऑप्टिकल स्टोर एवं क्लिनिक",
          description: "स्वयं का विजन टेस्टिंग सेंटर और चश्मों की दुकान खोलने का शानदार अवसर।"
        }
      ],
      relatedCoursesTitle: "इस करियर के लिए बोर्ड से जुड़े कोर्सेज",
      relatedCourses: [
        {
          code: "DOT",
          title: "डिप्लोमा इन ऑप्टोमेट्री टेक्नोलॉजी",
          duration: "2 वर्ष",
          eligibility: "10+2 (साइंस / PCB/PCM)",
          href: "/courses"
        },
        {
          code: "COT",
          title: "सर्टिफिकेट इन ऑप्थैल्मिक टेक्नोलॉजी",
          duration: "1 वर्ष",
          eligibility: "10वीं / 10+2 उत्तीर्ण",
          href: "/courses"
        }
      ],
      ctaTitle: "क्या आप दृष्टि विज्ञान एवं ऑप्टोमेट्री में अपना करियर बनाना चाहते हैं?",
      ctaDescription: "इंडियन पैरामेडिकल बोर्ड ऑफ इंडिया के संबद्ध संस्थानों से मान्यता प्राप्त डिप्लोमा कोर्स में प्रवेश लें।",
      ctaButtonText: "कोर्सेज देखें एवं आवेदन करें"
    }
  },
  {
    id: 7,
    slug: "nursing-assistant",
    image: "/Meditech7.jpeg",
    stats: {
      durationEn: "6 Months - 1 Year",
      durationHi: "6 माह से 1 वर्ष",
      eligibilityEn: "10th / 10+2 Pass (Any Stream)",
      eligibilityHi: "10वीं / 10+2 उत्तीर्ण (कोई भी संकाय)",
      salaryEn: "₹16,000 - ₹38,000 / mo",
      salaryHi: "₹16,000 - ₹38,000 प्रति माह",
      demandEn: "Highest Demand",
      demandSubEn: "Hospitals & Home Care",
      demandHi: "सर्वाधिक मांग",
      demandSubHi: "अस्पताल व होम हेल्थकेयर",
    },
    en: {
      title: "Nursing Assistant & General Duty Assistant (GDA)",
      tagline: "The Compassionate Frontline Heart of Inpatient Care and Bedside Support",
      badge: "Direct Patient Care Specialization",
      aboutTitle: "About the Nursing Assistant Profession",
      aboutParagraphs: [
        "Nursing Assistants, also known as General Duty Assistants (GDA), are the primary caregivers providing essential bedside support to hospitalized, elderly, postoperative, and bedridden patients. They bridge the vital communication gap between patients, staff nurses, and doctors.",
        "They are rigorously trained in measuring vital signs (blood pressure, temperature, pulse, oxygen saturation), patient hygiene, bedsore prevention, catheter care, feeding assistance, and emergency mobility transfers in both hospital wards and home healthcare environments."
      ],
      rolesTitle: "Key Roles & Responsibilities",
      rolesDescription: "Essential compassionate care duties provided daily in healthcare facilities:",
      roles: [
        {
          title: "Vital Signs Recording",
          description: "Accurately record patient blood pressure, heart rate, temperature, and SpO2 at prescribed hourly intervals."
        },
        {
          title: "Patient Hygiene & Bed Care",
          description: "Assist bedridden patients with sponge baths, oral hygiene, linen changes, and pressure ulcer (bedsore) prevention."
        },
        {
          title: "Nutrition & Medication Support",
          description: "Assist with patient feeding, oral medication reminders, and monitoring fluid intake and output charts."
        },
        {
          title: "Patient Mobilization & Transfer",
          description: "Safely transfer patients between hospital beds, wheelchairs, and stretchers using correct ergonomic lifting techniques."
        },
        {
          title: "Infection Control & Waste Segregation",
          description: "Disinfect patient surroundings and segregate biomedical waste into color-coded bins according to hospital norms."
        },
        {
          title: "Emergency Alert & BLS Support",
          description: "Promptly recognize clinical deterioration, alert nursing supervisors, and assist in basic first aid and CPR."
        }
      ],
      ladderTitle: "Career Progression Pathway",
      ladderSteps: [
        {
          step: "01",
          role: "Trainee Nursing Assistant (GDA)",
          experience: "0 - 1 Year",
          description: "Assisting staff nurses with basic patient comfort, hygiene, and room cleanliness."
        },
        {
          step: "02",
          role: "General Duty Nursing Assistant",
          experience: "1 - 3 Years",
          description: "Managing inpatient ward rounds, vital monitoring, mobility assistance, and feeding."
        },
        {
          step: "03",
          role: "Senior Patient Care Coordinator",
          experience: "3 - 6 Years",
          description: "Supervising ward caregiver teams, handling post-operative home health care, and specialized eldercare."
        },
        {
          step: "04",
          role: "Patient Services Supervisor",
          experience: "6+ Years",
          description: "Managing hospital floor nursing assistant rosters, patient satisfaction, and care protocols."
        }
      ],
      skillsTitle: "Key Technical & Clinical Skills Acquired",
      skills: [
        "Vital Signs Monitoring (BP, Pulse, SpO2, Temp)",
        "Bedside Hygiene & Bedsore Prevention",
        "Ergonomic Patient Transfer Techniques",
        "Enteral Tube Feeding Assistance",
        "Fluid Intake & Output Charting",
        "Biomedical Waste Segregation",
        "Basic Life Support (BLS) & First Aid",
        "Empathetic Communication & Elderly Care"
      ],
      sectorsTitle: "Top Employment Sectors",
      sectors: [
        {
          name: "Government & Private Hospitals",
          description: "General inpatient wards, emergency triage, ICU step-down, and recovery suites."
        },
        {
          name: "Home Healthcare & Post-Op Recovery Services",
          description: "Specialized in-home caregiver support for elderly and recovering patients."
        },
        {
          name: "Geriatric Care & Senior Living Facilities",
          description: "Assisted living homes and palliative hospice care centers."
        },
        {
          name: "Rehabilitation & Long-Term Recovery Centers",
          description: "Assisting patients undergoing prolonged physical therapy and stroke recovery."
        }
      ],
      relatedCoursesTitle: "Board Certified Courses for this Career",
      relatedCourses: [
        {
          code: "CGDA",
          title: "Certificate in General Duty Assistant (GDA)",
          duration: "6 Months / 1 Year",
          eligibility: "10th Pass",
          href: "/courses"
        },
        {
          code: "CDNA",
          title: "Diploma in Nursing Assistant",
          duration: "1 Year / 2 Years",
          eligibility: "10th / 10+2 Pass",
          href: "/courses"
        }
      ],
      ctaTitle: "Start a Noble Career in Bedside Healthcare & Patient Care",
      ctaDescription: "Enrol in board-recognized General Duty Assistant and Nursing Assistant programs to start working quickly in reputable hospitals.",
      ctaButtonText: "Explore Courses & Apply"
    },
    hi: {
      title: "नर्सिंग असिस्टेंट एवं जनरल ड्यूटी असिस्टेंट (GDA)",
      tagline: "अस्पतालों में मरीजों की सेवा, प्राथमिक देखभाल और बेडसाइड सपोर्ट का सबसे मानवीय आधार",
      badge: "प्रत्यक्ष मरीज देखभाल विशेषज्ञता",
      aboutTitle: "नर्सिंग असिस्टेंट करियर का परिचय",
      aboutParagraphs: [
        "नर्सिंग असिस्टेंट, जिन्हें जनरल ड्यूटी असिस्टेंट (GDA) भी कहा जाता है, अस्पतालों और स्वास्थ्य केंद्रों में मरीजों की दैनिक देखभाल के सबसे मजबूत आधार होते हैं। वे डॉक्टर और स्टाफ नर्सों की देखरेख में मरीजों को समय पर दवाइयां देने, खाना खिलाने, सफाई रखने और उनकी शारीरिक स्थिति पर नजर रखने का काम करते हैं।",
        "यह एक ऐसा करियर है जिसे 10वीं पास करने के बाद बेहद कम समय (6 माह से 1 वर्ष) में पूरा करके तुरंत किसी भी प्रतिष्ठित अस्पताल, नर्सिंग होम या होम हेल्थकेयर में रोजगार पाया जा सकता है।"
      ],
      rolesTitle: "मुख्य कार्य एवं जिम्मेदारियाँ",
      rolesDescription: "अस्पताल के वार्डों में प्रतिदिन निभाई जाने वाली आवश्यक जिम्मेदारियां:",
      roles: [
        {
          title: "वाइटल साइंस (Vitals) की नियमित जांच",
          description: "मरीज का ब्लड प्रेशर (BP), नब्ज (Pulse), तापमान और ऑक्सीजन स्तर (SpO2) समय-समय पर नापना और रिकॉर्ड करना।"
        },
        {
          title: "मरीज की स्वच्छता एवं बेड केयर",
          description: "बिस्तर पर लेटे मरीजों को स्पंज बाथ देना, कपड़े बदलना और लंबे समय तक लेटे रहने से होने वाले छालों (Bedsore) से बचाना।"
        },
        {
          title: "भोजन एवं दवाइयों में सहयोग",
          description: "मरीज को समय पर पोषक आहार खिलाना, पानी पिलाना और डॉक्टर द्वारा बताई गई दवाइयां समय पर याद दिलाना।"
        },
        {
          title: "मरीज का स्थानांतरण (Patient Mobility)",
          description: "मरीज को सुरक्षित तरीके से व्हीलचेयर, स्ट्रेचर या बेड पर ले जाना और टेस्ट्स के लिए ले जाने में मदद करना।"
        },
        {
          title: "संक्रमण नियंत्रण व कचरा प्रबंधन",
          description: "मरीज के आसपास स्वच्छता बनाए रखना और अस्पताल के बायोमेडिकल कचरे को सही रंगों के डस्टबिन में डालना।"
        },
        {
          title: "आपातकालीन स्थिति में तुरंत सूचना",
          description: "मरीज की तबीयत अचानक बिगड़ने पर तुरंत ड्यूटी डॉक्टर या सीनियर नर्स को सूचित करना और प्राथमिक उपचार देना।"
        }
      ],
      ladderTitle: "करियर में पदोन्नति एवं विकास क्रम",
      ladderSteps: [
        {
          step: "01",
          role: "ट्रेनी जनरल ड्यूटी असिस्टेंट",
          experience: "0 - 1 वर्ष",
          description: "सीनियर नर्सों की देखरेख में मरीजों के बेड बदलना, वाइटल्स नापना और वार्ड के नियमों को समझना।"
        },
        {
          step: "02",
          role: "जनरल ड्यूटी नर्सिंग असिस्टेंट",
          experience: "1 - 3 वर्ष",
          description: "स्वतंत्र रूप से इनपेशेंट वार्ड में मरीजों की देखभाल, खानपान और दैनिक रिपोर्टिंग करना।"
        },
        {
          step: "03",
          role: "सीनियर पेशेंट केयर कोऑर्डिनेटर",
          experience: "3 - 6 वर्ष",
          description: "होम हेल्थकेयर में गंभीर मरीजों की देखभाल और नए केयरगिवर्स का मार्गदर्शन।"
        },
        {
          step: "04",
          role: "पेशेंट सर्विसेज सुपरवाइजर",
          experience: "6+ वर्ष",
          description: "अस्पताल के पूरे वार्ड के असिस्टेंट्स की ड्यूटी तय करना और पेशेंट केयर की गुणवत्ता सुनिश्चित करना।"
        }
      ],
      skillsTitle: "प्रशिक्षण के दौरान अर्जित मुख्य कौशल",
      skills: [
        "वाइटल साइंस मापन (BP, Pulse, SpO2, Temp)",
        "बेडसाइड स्वच्छता एवं बेडसोर की रोकथाम",
        "मरीज को उठाने व व्हीलचेयर ट्रांसफर की सही तकनीक",
        "तरल पदार्थ इनटेक व आउटपुट चार्टिंग",
        "बायोमेडिकल वेस्ट मैनेजमेंट",
        "फर्स्ट एड एवं बेसिक लाइफ सपोर्ट (BLS)",
        "सहानुभूतिपूर्ण मरीज संवाद",
        "बुजुर्गों एवं गंभीर मरीजों की विशेष देखभाल"
      ],
      sectorsTitle: "प्रमुख रोजगार क्षेत्र",
      sectors: [
        {
          name: "सरकारी एवं निजी अस्पताल व नर्सिंग होम्स",
          description: "सामान्य वार्ड्स, आईसीयू सपोर्ट और इमरजेंसी रूम्स में चौबीसों घंटे मांग।"
        },
        {
          name: "होम हेल्थकेयर एवं पोस्ट-ऑपरेटिव केयर",
          description: "ऑपरेशन के बाद घर पर मरीजों की निजी देखभाल करने वाली प्रतिष्ठित एजेंसियां।"
        },
        {
          name: "वृद्धाश्रम एवं सीनियर सिटिजन होम्स",
          description: "बुजुर्गों की दैनिक देखभाल और दवाइयों के प्रबंधन का संवेदनशील कार्य।"
        },
        {
          name: "रिहैबिलिटेशन एवं फिजियोथेरेपी सेंटर्स",
          description: "दुर्घटना या लकवे के बाद उबर रहे मरीजों की रिकवरी में सहायता।"
        }
      ],
      relatedCoursesTitle: "इस करियर के लिए बोर्ड से जुड़े कोर्सेज",
      relatedCourses: [
        {
          code: "CGDA",
          title: "सर्टिफिकेट इन जनरल ड्यूटी असिस्टेंट (GDA)",
          duration: "6 माह / 1 वर्ष",
          eligibility: "10वीं उत्तीर्ण",
          href: "/courses"
        },
        {
          code: "CDNA",
          title: "डिप्लोमा इन नर्सिंग असिस्टेंट",
          duration: "1 वर्ष / 2 वर्ष",
          eligibility: "10वीं / 10+2 उत्तीर्ण",
          href: "/courses"
        }
      ],
      ctaTitle: "क्या आप सेवा और सम्मान से भरपूर स्वास्थ्य क्षेत्र में करियर बनाना चाहते हैं?",
      ctaDescription: "कम समय में नौकरी पाने के लिए इंडियन पैरामेडिकल बोर्ड ऑफ इंडिया के जीडीए/नर्सिंग असिस्टेंट कोर्स में दाखिला लें।",
      ctaButtonText: "कोर्सेज देखें एवं आवेदन करें"
    }
  }
];

export function getCareerBySlug(slug: string): CareerItem | undefined {
  return CAREERS_DATA.find((c) => c.slug === slug);
}

export function getAllCareerSlugs(): string[] {
  return CAREERS_DATA.map((c) => c.slug);
}
